name: Update

on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      tmate:
        description: Start a tmate session
        type: boolean
        default: false
        required: false
      nuke:
        description: Rebuild full commit history
        type: boolean
        default: false
        required: false
  schedule:
    - cron: '11 8 * * *' # daily

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Checkout sdk branch
        id: checkout-sdk
        uses: actions/checkout@v6
        with:
          ref: sdk
          path: sdk
          fetch-depth: '0'
          fetch-tags: 'true'

      - name: Start tmate
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.tmate }}

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
          cache: pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Restore download cache
        uses: actions/cache/restore@v6
        with:
          path: download
          key: ${{ steps.checkout-sdk.outputs.commit }}

      - name: Restore cookies
        id: restore-cookies
        run: |
          python <<'PYTHON'
          from hashlib import sha256
          from os import environ
          data = environ['COOKIES'].encode('utf-8')
          print(f'Size: {len(data)}, SHA256: {sha256(data).hexdigest()}')
          with open('cookies.json', 'wb') as f: f.write(data)
          PYTHON
        env:
          COOKIES: ${{ secrets.COOKIES }}

      - name: Update
        id: update
        run: |
          ./generate.py sdk --log-level debug \
            --git-commit-arg=--author="Valve <questions@valvesoftware.com>" \
            ${{ case(github.event_name == 'workflow_dispatch' && inputs.nuke, '--nuke', '') }}
        env:
          STEAM_LOGIN: ${{ secrets.STEAM_LOGIN }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
          STEAM_SHARED_SECRET: ${{ secrets.STEAM_SHARED_SECRET }}
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com

      - name: Save download cache
        if: ${{ steps.update.outputs.commit != steps.checkout-sdk.outputs.commit }}
        uses: actions/cache/save@v6
        with:
          path: download
          key: ${{ steps.update.outputs.commit }}

      - name: Save cookies
        if: ${{ !cancelled() && steps.restore-cookies.conclusion == 'success' }}
        run: |
          python <<'PYTHON'
          from hashlib import sha256
          with open('cookies.json', 'rb') as f: data = f.read()
          print(f'Size: {len(data)}, SHA256: {sha256(data).hexdigest()}')
          PYTHON
          gh secret set COOKIES < cookies.json
        env:
          GH_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}

      - name: Define remote
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.nuke }}
        run: git -C sdk remote add origin ${{ github.repositoryUrl }}

      - name: Push
        if: ${{ steps.update.outputs.has-new == '1' && steps.update.outputs.reset != '1' }}
        run: |
          git -C sdk push --progress --verbose --set-upstream origin sdk

      - name: Force push
        if: ${{ steps.update.outputs.reset == '1' }}
        run: |
          git -C sdk push --force --progress --verbose --set-upstream origin sdk

      - name: Push tags
        if: ${{ steps.update.outputs.has-new == '1' || steps.update.outputs.reset == '1' }}
        run: |
          for tag in $(git -C sdk ls-remote --tags origin | sed -E 's|.+refs/tags/||'); do
            if ! git -C sdk merge-base --is-ancestor "refs/tags/$tag" sdk; then
              echo "Deleting tag $tag"
              git -C sdk tag --delete "$tag"
              git -C sdk push origin --delete "refs/tags/$tag"
            fi
          done
          git -C sdk push --verbose --force --tags

      - name: Notify about changes
        if: ${{ steps.update.outputs.has-new == '1' || steps.update.outputs.reset == '1' }}
        uses: dawidd6/action-send-mail@v16
        with:
          connection_url: ${{ secrets.MAIL_CONNECTION }}
          subject: >
            [${{ github.repository }}]
            ${{ case(steps.update.outputs.reset == '1', 'Branch sdk was force-pushed to', steps.update.outpus.new-commit-count) }}
            ${{ case(steps.update.outputs.reset == '1', steps.update.outputs.commit-short, 'new commit') }}
          from: ${{ secrets.MAIL_FROM }}
          to: ${{ secrets.MAIL_TO }}
          bcc: ${{ secrets.MAIL_BCC }}
          html_body: |
            Diff:

            ```diff
            ${{ steps.update.outputs.diff }}
            ```

            [Compare changes](https://github.com/${{ github.repository }}/compare/${{ steps.checkout-sdk.outputs.commit }}...${{ steps.update.outputs.commit }})
          convert_markdown: true
