name: Update

on:
  workflow_dispatch:
    inputs:
      tmate:
        description: 'Start a tmate session'
        default: 'false'
        required: false
  schedule:
    - cron: '11 8 * * *' # daily

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Checkout sdk branch
        id: checkout-sdk
        uses: actions/checkout@v6
        with:
          ref: sdk
          path: sdk
          fetch-depth: '0'
          fetch-tags: 'true'

      - name: Start tmate
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.tmate == 'true' }}

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
          cache: pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Restore download cache
        uses: actions/cache/restore@v5
        with:
          path: download
          key: ${{ steps.checkout-sdk.outputs.commit }}

      - name: Restore cookies
        run: echo "$COOKIES" > cookies.json
        env:
          COOKIES: ${{ secrets.COOKIES }}

      - name: Update
        id: update
        run: ./generate.py sdk --git-commit-arg=--author="Valve <questions@valvesoftware.com>" --log-level debug
        env:
          COOKIES: ${{ secrets.COOKIES }}
          STEAM_LOGIN: ${{ secrets.STEAM_LOGIN }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
          STEAM_SHARED_SECRET: ${{ secrets.STEAM_SHARED_SECRET }}
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_DATE: "2085-11-08T00:00:00+00:00"

      - name: Save download cache
        uses: actions/cache/save@v5
        with:
          path: download
          key: ${{ steps.update.outputs.commit }}

      - name: Save cookies
        run: gh secret set COOKIES < cookies.json
        env:
          GH_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}

      - name: Push
        if: ${{ steps.update.outputs.has-new == '1' && steps.update.outputs.reset != '1' }}
        run: |
          git -C sdk push --progress --verbose --set-upstream origin sdk

      - name: Force push
        if: ${{ steps.update.outputs.reset == '1' }}
        run: |
          git -C sdk push --force --progress --verbose --set-upstream origin sdk

      - name: Push tags
        if: ${{ steps.update.outputs.has-new == '1' || steps.update.outputs.reset }}
        run: |
          for tag in $(git -C sdk ls-remote --tags origin | sed -E 's|.+refs/tags/||'); do
            if ! git -C sdk merge-base --is-ancestor "refs/tags/$tag" sdk; then
              echo "Deleting tag $tag"
              git -C sdk tag --delete "$tag"
              git -C sdk push origin --delete "refs/tags/$tag"
            fi
          done
          git -C sdk push --verbose --force --tags

      - name: Notify about force push
        uses: dawidd6/action-send-mail@v16
        if: ${{ steps.update.outputs.reset == '1' }}
        with:
          connection_url: ${{ secrets.MAIL_CONNECTION }}
          subject: "[${{ github.repository }}] Branch sdk was force-pushed to ${{ steps.update.outputs.commit-short }}"
          from: ${{ secrets.MAIL_FROM }}
          to: ${{ secrets.MAIL_TO }}
          bcc: ${{ secrets.MAIL_BCC }}
          html_body: |
            Diff:

            ```diff
            ${{ steps.update.outputs.diff }}
            ```

            [Compare changes](https://github.com/${{ github.repository }}/compare/${{ steps.checkout-sdk.outputs.commit }}...${{ steps.update.outputs.commit }})
          convert_markdown: true
